### ISSUE TITLE
sudo sfputil does not work on z9100

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-platform-modules-dell#11]
```
admin@str-z9100-acs-1:~$ sudo sfputil
error reading port info ([Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-dell_z9100_c2538-r0/Traceback (most recent call last):\n  File "/usr/local/bin/sonic-cfggen", line 116, in <module>\n    main()\n  File "/usr/local/bin/sonic-cfggen", line 78, in main\n    data.update(parse_xml(minigraph, data[\'platform\']))\n  File "/usr/local/lib/python2.7/dist-packages/minigraph.py", line 397, in parse_xml\n    root = ET.parse(filename).getroot()\n  File "lxml.etree.pyx", line 3299, in lxml.etree.parse (src/lxml/lxml.etree.c:72655)\n  File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106263)\n  File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106564)\n  File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105561)\n  File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100456)\n  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543)\n  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003)\n  File "parser.pxi", line 618, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95015)\nIOError: Error reading file \'/etc/sonic/minigraph.xml\': failed to load external entity "/etc/sonic/minigraph.xml"/portmap.ini')
admin@str-z9100-acs-1:~$ 
```

**Comment by lguohan** [comment]
fi
