### ISSUE TITLE
sfputil breaks on s6100 and z9100

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-platform-modules-dell#16]
due to recent changes on https://github.com/Azure/sonic-buildimage/commit/178fc032ae45a17170a2c4fb22d0569dc139b63c

please also add support for SFP presence, low-power mode and reset

**Comment by lguohan** [comment]
admin@str-s6100-acs-5:~$ sudo sfputil show
Traceback (most recent call last):
  File "/usr/bin/sfputil", line 9, in <module>
    load_entry_point('sonic-utilities==1.1', 'console_scripts', 'sfputil')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 371, in cli
    err = load_platform_sfputil()
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 343, in load_platform_sfputil
    module = imp.load_source(PLATFORM_SPECIFIC_MODULE_NAME, module_file)
  File "/usr/share/sonic/device/x86_64-dell_s6100_c2538-r0/plugins/sfputil.py", line 6, in <module>
    raise ImportError (str(e) + "- required module not found")
ImportError: cannot import name sfputilbase- required module not found
